# Generated by Django 6.1 on 2026-08-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_options_alter_bookingitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Тривалість бронювання в хвилинах (за замовчуванням 2 години)'),
        ),
    ]
