# Generated by Django 6.1 on 2026-08-14 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_gamepromocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_booking', to='restaurant.gamepromocode'),
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gamepromocode',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
